projectcoffee/cafesubmission/urls.py
from django.urls import path
from . import views

app_name = 'cafesubmission'

urlpatterns = [
    path('', views.cafesubmission, name='cafesubmission'),
    path('draft/', views.draftcafesubmission, name='draftcafesubmission'),
    path('cafesubmission_approve/<int:pk>', views.cafesubmission_approve, name='cafesubmission_approve'),
    path('cafesubmission_delete/<int:pk>', views.cafesubmission_delete, name='cafesubmission_delete'),
]

projectcoffee/coffeeshoplist/urls.py
from django.urls import path
from . import views
from django.urls import include
from .views import register, login
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.coffeeshoplist, name='coffeeshoplist'),
    path('register/', views.register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', views.login, name='login'),
    path('accounts/logout/',  auth_views.LogoutView.as_view(), name='logout'),
    path('rate_shop/<int:coffee_shop_id>/', views.rate_coffee_shop, name='rate_shop'),
    path('shop_reviews/<int:coffee_shop_id>/', views.shopreviews, name='shop_reviews'),
]

projectcoffee/projectcoffee/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coffeeshoplist.urls')),
    path('cafesubmission/', include('cafesubmission.urls' ,namespace='cafesubmission')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectcoffee/cafesubmission/models.py

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


class CafeSubmission(models.Model):
  name = models.CharField(max_length=100)
  address = models.CharField(max_length=255)
  phone = models.CharField(max_length=100)    
  website = models.CharField(max_length=100)
  email = models.CharField(max_length=100)
  description = models.CharField(max_length=100)
  hours = models.CharField(max_length=100)
  image = models.ImageField(upload_to='coffee_shop_images/', default='coffee_shop_images/default.jpg')
  submitted_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cafe_submissions')

  def __str__(self):
        return self.name

projectcoffee/coffeeshoplist/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.\
class CoffeeShop(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=100)
    website = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    hours = models.CharField(max_length=100)
    image = models.ImageField(upload_to='coffee_shop_images/', default='coffee_shop_images/default.jpg')
class Rating(models.Model):
    coffee_shop = models.ForeignKey(CoffeeShop, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    review = models.TextField(blank=True)

projectcoffee/cafesubmission/forms.py
from django import forms
from .models import CafeSubmission

class CafeSubmissionForm(forms.ModelForm):

    class Meta:
        model = CafeSubmission
        fields = ('name', 'description', 'email', 'address', 'website' , 'hours', 'phone', 'image',)

    


projectcoffee/coffeeshoplist/forms.py
from django import forms
from .models import Rating
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['rating', 'review']
 
class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


projectcoffee/cafesubmission/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required 
from django.shortcuts import render, redirect
from .forms import CafeSubmissionForm
from .models import CafeSubmission
from coffeeshoplist.models import CoffeeShop
from .decorators import admin_required
from django.shortcuts import get_object_or_404
from django.urls import reverse



@login_required
def cafesubmission(request):
    if request.method == "POST":
        form = CafeSubmissionForm(request.POST, request.FILES)
        if form.is_valid():
            cafe_submission = form.save(commit=False)
            cafe_submission.submitted_by = request.user
            cafe_submission.save()
            messages.success(request, 'Thank you for submitting a coffee shop!')
            return redirect('cafesubmission:cafesubmission')
    else:
        form = CafeSubmissionForm()
    return render(request, 'cafesubmission.html', {'form': form})

# admin only view
@admin_required
def draftcafesubmission(request):
    submissions = CafeSubmission.objects.all()
    return render(request, 'draftcafesubmission.html', {'submissions': submissions})

@admin_required
def cafesubmission_approve(request, pk):
    submission = get_object_or_404(CafeSubmission, pk=pk)

    # create new coffee shop instance
    coffee_shop = CoffeeShop()
    coffee_shop.name = submission.name
    coffee_shop.description = submission.description
    coffee_shop.address = submission.address
    coffee_shop.website = submission.website
    coffee_shop.hours = submission.hours
    coffee_shop.phone = submission.phone
    coffee_shop.image = submission.image
    coffee_shop.save()

    # delete the submission
    submission.delete()

    messages.success(request, 'The coffee shop has been approved and added to the list!')
    return redirect('/')

# admin only view
@admin_required
def cafesubmission_delete(request, pk):
    submission = get_object_or_404(CafeSubmission, pk=pk)
    submission.delete()
    messages.success(request, 'The coffee shop submission has been deleted!')
    return redirect('caffesubmisions/draft')



projectcoffee/coffeeshoplist/views.py
from django.shortcuts import render, redirect
from .models import CoffeeShop, Rating
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .forms import RatingForm
from .forms import UserRegistrationForm

def coffeeshoplist(request):
    coffee_shops = CoffeeShop.objects.all()
    ratings = Rating.objects.all()
    rating_dict = {}
    for rating in ratings:
        rating_dict.setdefault(rating.coffee_shop_id, []).append(rating.rating)
    avg_ratings = {}
    for coffee_shop in coffee_shops:
        ratings_list = rating_dict.get(coffee_shop.id, [])
        avg_rating = round(sum(ratings_list) / max(len(ratings_list), 1), 2) if ratings_list else '-'
        avg_ratings[coffee_shop.id] = avg_rating
    return render(request, 'coffeeshoplist.html', {'coffee_shops': coffee_shops, 'avg_ratings': avg_ratings})


# view for all the reviews of a coffee shop
def shopreviews(request, coffee_shop_id):
    coffee_shop = CoffeeShop.objects.get(id=coffee_shop_id)
    ratings = Rating.objects.filter(coffee_shop=coffee_shop)
    return render(request, 'shop_reviews.html', {'coffee_shop': coffee_shop, 'ratings': ratings})


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserRegistrationForm()
    return render(request, 'register.html', {'form': form})

def login(request):
    template = loader.get_template('login.html')
    return HttpResponse(template.render({}, request))

@login_required
def rate_coffee_shop(request, coffee_shop_id):
    coffee_shop = CoffeeShop.objects.get(id=coffee_shop_id)
    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            rating.coffee_shop = coffee_shop
            rating.user = request.user
            rating.save()
            return redirect('coffeeshoplist')
    else:
        form = RatingForm()
    return render(request, 'rate_shop.html', {'form': form, 'coffee_shop': coffee_shop})
 
 
        
    






projectcoffee/cafesubmission/templates/cafesubmission.html
{% extends 'base.html' %} {% block content %}
<h2>Submit a New Cafe</h2>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Submit</button>
  {% if message %} {{ message }} {% endif %}
</form>
{% endblock %}

projectcoffee/cafesubmission/templates/draftcafesubmission.html
{% extends 'base.html' %} {% block content %}
<h2>Cafe Shop Draft List</h2>
{% for cafesubmission in submissions %}
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">{{ cafesubmission.name }}</h5>
    <div class="card mx-2 my-2" style="width: 30rem">
      <img
        src="{{ cafesubmission.image.url }}"
        class="card-img-top"
        alt="{{ cafesubmission.name }}"
      />
    </div>
    <div class="card-body">
      <h6 class="card-subtitle mb-2 text-muted">{{ cafesubmission.phone }}</h6>
      <h6 class="card-subtitle mb-2 text-muted">
        {{ cafesubmission.address }}
      </h6>
      <p class="card-text">{{ cafesubmission.description }}</p>
      <p class="card-text">{{ cafesubmission.email }}</p>
    </div>
    <div class="card-footer">
      <a
        href="{% url 'cafesubmission:cafesubmission_approve' pk=cafesubmission.pk %}"
        class="btn btn-primary"
        >Approved</a
      >
      <a
        href="{% url 'cafesubmission:cafesubmission_delete' pk=cafesubmission.pk %}"
        class="btn btn-danger"
        >Reject</a
    </div>
  </div>
</div>
{% endfor %} {% endblock %}

projectcoffee/coffeeshoplist/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}ReviewMyCafe</title>
    <link rel="icon" href="../../media/assets/cafe.png" />
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
        <img src="../../media/assets/cafe.png" width="30" height="30" alt="" />
        ReviewMyCafe</a
      >
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link">Welcome, {{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a
              class="btn btn-danger"
              href="{% url 'logout' %}?next=/accounts/login/"
            >
              Logout
            </a>
            {% else %}
          </li>
          <li class="nav-item {% block login_active %}{% endblock %}">
            <a type="button" class="btn btn-success" href="{% url 'login' %}">
              Login
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <container
      ><div class="container mt-4">
        {% block content %}{% endblock %}
      </div></container
    >

    <style>
      footer {
        position: relative;
        bottom: 0;
        width: 100%;
        background-color: white;
        text-align: center;
      }
    </style>

    <!-- footer -->
    <footer class="py-3 footer mt-5">
      <div class="container">
      <p class="text-center text-muted">&copy; 2023 made for cafe hunters by @aniqaqill</p>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
  </body>
</html>

projectcoffee/coffeeshoplist/templates/coffeeshoplist.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
  <head>
    <title>Coffee Shop List</title>
  </head>
  <body>
    {% block content %}
    <h1>Coffee Shop List</h1>
    <ul class="d-flex flex-wrap">
      {% for coffee_shop in coffee_shops %}
      <div class="card mx-2 my-2" style="width: 20rem">
        <img
          src="{{ coffee_shop.image.url }}"
          class="card-img-top"
          alt="{{ coffee_shop.name }}"
        />
        <div class="card-body">
          <h5 class="card-title">{{ coffee_shop.name }}</h5>
          <p class="card-text">{{ coffee_shop.description}}</p>
          <p class="card-text">{{ coffee_shop.address}}</p>
          <p class="card-text">{{ coffee_shop.phone}}</p>
          <p class="card-text">{{ coffee_shop.email}}</p>
        </div>

        <div class="card-footer">
          <a href="{% url 'rate_shop' coffee_shop.id %}" class="btn btn-primary"
            >Rate</a
          >
          <a
            href="{{ coffee_shop.website}}"
            target="_blank"
            class="btn btn-primary"
            >Websites</a
          >
          <a
            href="{% url 'shop_reviews' coffee_shop.id %}"
            class="btn btn-primary"
            >Reviews</a
          >
        </div>
      </div>

      {% endfor %}
    </ul>
    <!-- Make a section where user can submit cafe application form -->
    <div class="d-flex justify-content-center">
      <a href="/cafesubmission" class="btn btn-dark">Submit a Cafe</a>
    </div>

    {% endblock %}
  </body>
</html>

projectcoffee/coffeeshoplist/templates/rate_shop.html
{% extends 'base.html' %}
<DOCTYPE html>
  <html>
    <head>
      <title>Coffee Shop List</title>
    </head>
    <body>
      {% block content %}
      <h1>Rate {{ coffee_shop.name }}</h1>
      <div class="card mb-3">
        <img
          src="{{ coffee_shop.image.url }}"
          class="card-img-top"
          alt="{{ coffee_shop.name }}"
          style="height: 300px; object-fit: cover"
        />
        <div class="card-body">
          <h5 class="card-title">{{ coffee_shop.name }}</h5>
          <p class="card-text">
            {{ coffee_shop.name }} is a {{ coffee_shop.description }}.
          </p>
          <p class="card-text">{{ coffee_shop.address }}</p>
        </div>
      </div>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="Rating">Rating</label>
          <div class="rating">
            <input type="radio" name="rating" id="star1" value="1" />
            <label for="star1" class="fa fa-star"></label>
            <input type="radio" name="rating" id="star2" value="2" />
            <label for="star2" class="fa fa-star"></label>
            <input type="radio" name="rating" id="star3" value="3" />
            <label for="star3" class="fa fa-star"></label>
            <input type="radio" name="rating" id="star4" value="4" />
            <label for="star4" class="fa fa-star"></label>
            <input type="radio" name="rating" id="star5" value="5" />
            <label for="star5" class="fa fa-star"></label>
          </div>
        </div>
        <!-- review -->
        <div class="form-group">
          <label for="review">Review</label>
          <textarea
            class="form-control"
            id="review"
            name="review"
            rows="3"
          ></textarea>
        </div>

        <button type="submit">Submit</button>
      </form>
      {% endblock %}
    </body>
  </html>
</DOCTYPE>

projectcoffee/coffeeshoplist/templates/register.html
<!-- registrationpage -->
<!-- Path: projectcoffee\coffeeshoplist\templates\register.html -->
<!-- Compare this snippet from projectcoffee\coffeeshoplist\templates\coffeeshoplist.html: -->
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
  <head>
    <title>Registration</title>
  </head>
  <body>
    {% block content %}
    <main class="text-center form-signin w-25 m-auto h-100">
      <form method="post">
        <img
          class="mb-4"
          src="../../../media/assets/cafe.png"
          alt=""
          width="80"
          height="87"
        />
        <h1 class="h3 mb-3 fw-normal">Registration</h1>
        {% for field in form %} {% if field.errors %}
        <div class="alert alert-danger">
          {% for error in field.errors %}
          <strong>{{ error|escape }}</strong><br />
          {% endfor %}
        </div>
        {% endif %} {% endfor %} {% csrf_token %}
        <div class="form-group">
          <label class="control-label" for="{{ form.username.id_for_label }}"
            >Username:</label
          >
          <div class="card">{{ form.username }}</div>
        </div>
        <div class="form-group">
          <label class="control-label" for="{{ form.password1.id_for_label }}"
            >Password:</label
          >
          <div class="card">{{ form.password1 }}</div>
        </div>
        <div class="form-group">
          <label class="control-label" for="{{ form.password2.id_for_label }}"
            >Confirm Password:</label
          >
          <div class="card">{{ form.password2 }}</div>
        </div>

        <div class="form-group">
          <label class="control-label" for="{{ form.email.id_for_label }}"
            >Email:</label
          >
          <div class="card">{{ form.email }}</div>
        </div>

        <button class="w-100 btn btn-lg btn-primary" type="submit">
          Register
        </button>
        <p>
          Already have an account? <a href="{% url 'login' %}">Log in here</a>
        </p>
      </form>
    </main>
    {% endblock %}
  </body>
</html>

projectcoffee/coffeeshoplist/templates/shop_reviews.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
  <head>
    <title>Coffee Shop Rating</title>
  </head>
  <body>
    {% block content %}
    <h1>Coffee Shop Rating and Reviews</h1>
    <h2>{{ coffee_shop.name }}</h2>
 {% for rating in ratings %}
      <div class="card mx-2 my-2" style="width: 20rem">
        <div class="card-body">
          <!-- <h5 class="card-title">{{ rating.user }}</h5> -->
          <p class="card-text"> <Strong>Ratings :</Strong> {{ rating.rating }} / 5 </p>
          <p class="card-text"> <Strong>Reviews :</Strong> {{ rating.review }}</p>
        </div>
      </div>
      {% endfor %}
    </ul>
    {% endblock %}
  </body>
</html>